create table if not exists users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(512) not null
);

create table if not exists items (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(1000) not null,
    available bool not null default true,
    owner_id bigint not null REFERENCES users(id) ON DELETE CASCADE
);

create table if not exists bookings (
    id bigint generated by default as identity primary key,
    start_date timestamp not null,
    end_date timestamp not null,
    item_id bigint not null REFERENCES items(id) ON DELETE CASCADE,
    booker_id bigint not null REFERENCES users(id) ON DELETE CASCADE,
    status varchar not null default 'WAITING'
);

create table if not exists comments (
    id bigint generated by default as identity primary key,
    text varchar not null,
    item_id bigint not null REFERENCES items(id) ON DELETE CASCADE,
    author_id bigint not null REFERENCES users(id) ON DELETE CASCADE,
    created timestamp not null
);