create table if not exists users (
    id bigint generated by default as identity,
    name varchar(255) not null,
    email varchar(512) not null,
    constraint PK_USER primary key (id),
    constraint UNIQUE_USER_EMAIL unique (email)
);

create table if not exists items (
    id bigint generated by default as identity,
    name varchar(255) not null,
    description varchar(1000) not null,
    is_available boolean not null,
    owner_id bigint not null,
    constraint PK_ITEM primary key (id),
    constraint FK_ITEM_OWNER foreign key (owner_id) references users on delete cascade
);

create table if not exists bookings (
    id bigint generated by default as identity,
    start_date timestamp not null,
    end_date timestamp not null,
    item_id bigint not null,
    booker_id bigint not null,
    status varchar default 'WAITING' not null,
    constraint PK_BOOKING primary key (id),
    constraint FK_BOOKING_ITEM foreign key (item_id) references items on delete cascade,
    constraint FK_BOOKING_BOOKER foreign key (booker_id) references users on delete cascade
);

create table if not exists comments (
    id bigint generated by default as identity,
    text varchar not null,
    item_id bigint not null,
    author_id bigint not null,
    created timestamp not null,
    constraint PK_COMMENT primary key (id),
    constraint FK_COMMENT_ITEM foreign key (item_id) references items on delete cascade,
    constraint FK_COMMENT_AUTHOR foreign key (author_id) references users on delete cascade
);